to do ticket Edit Member
lethu96/testapp- pull request #10
Opened 2018-02-12 07:42 UTC by lethu96

2018-02-12 07:48 UTC, jackdiff requested changes

2018-02-12 07:48 UTC, jackdiff commented on app/Http/Controllers/MemberController.php
> +                $member->position_id = $data['position_id'];
wrong indent

2018-02-13 08:25 UTC, hieutq commented on resources/assets/js/components/CreateMember.js
> +            console.log(error);})
Pls remove this code. And Pls remove all "console.log" in all files.

2018-02-20 13:04 UTC, hieutq approved these changes

2018-02-21 03:24 UTC, merged